// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostAndFoundApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250807060057_AddLogsTable")]
    partial class AddLogsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("LostAndFoundApp.Models.LineCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LineCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Line = "M1"
                        },
                        new
                        {
                            Id = 2,
                            Line = "M2"
                        },
                        new
                        {
                            Id = 3,
                            Line = "M3"
                        },
                        new
                        {
                            Id = 4,
                            Line = "M4"
                        },
                        new
                        {
                            Id = 5,
                            Line = "M5"
                        },
                        new
                        {
                            Id = 6,
                            Line = "M6"
                        },
                        new
                        {
                            Id = 7,
                            Line = "M7"
                        },
                        new
                        {
                            Id = 8,
                            Line = "M8"
                        },
                        new
                        {
                            Id = 9,
                            Line = "M9"
                        },
                        new
                        {
                            Id = 10,
                            Line = "M10"
                        });
                });

            modelBuilder.Entity("LostAndFoundApp.Models.Logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Executor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("LostAndFoundApp.Models.LostItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoundBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FoundDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LineCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineCodeId");

                    b.ToTable("LostItems");
                });

            modelBuilder.Entity("LostAndFoundApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Admin123",
                            Rol = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Password1",
                            Rol = "Moderatör",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 3,
                            Password = "Password2",
                            Rol = "Moderatör",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = 4,
                            Password = "Test123",
                            Rol = "Moderatör",
                            UserName = "test"
                        },
                        new
                        {
                            Id = 5,
                            Password = "Demo123",
                            Rol = "Moderatör",
                            UserName = "demo"
                        });
                });

            modelBuilder.Entity("LostAndFoundApp.Models.LostItem", b =>
                {
                    b.HasOne("LostAndFoundApp.Models.LineCode", "LineCode")
                        .WithMany("LostItems")
                        .HasForeignKey("LineCodeId");

                    b.Navigation("LineCode");
                });

            modelBuilder.Entity("LostAndFoundApp.Models.LineCode", b =>
                {
                    b.Navigation("LostItems");
                });
#pragma warning restore 612, 618
        }
    }
}
