// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostAndFoundApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("LostAndFoundApp.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "admin",
                            Rol = "Admin",
                            Sifre = "admin123"
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "Ahmet Yılmaz",
                            Rol = "Kullanıcı",
                            Sifre = "123456"
                        },
                        new
                        {
                            Id = 3,
                            AdSoyad = "Mehmet Demir",
                            Rol = "Kullanıcı",
                            Sifre = "password"
                        },
                        new
                        {
                            Id = 4,
                            AdSoyad = "Ayşe Kaya",
                            Rol = "Moderatör",
                            Sifre = "test123"
                        },
                        new
                        {
                            Id = 5,
                            AdSoyad = "Fatma Özkan",
                            Rol = "Kullanıcı",
                            Sifre = "demo123"
                        });
                });

            modelBuilder.Entity("LostAndFoundApp.Models.LineCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LineCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Line = "M1"
                        },
                        new
                        {
                            Id = 2,
                            Line = "M2"
                        },
                        new
                        {
                            Id = 3,
                            Line = "M3"
                        },
                        new
                        {
                            Id = 4,
                            Line = "M4"
                        },
                        new
                        {
                            Id = 5,
                            Line = "M5"
                        },
                        new
                        {
                            Id = 6,
                            Line = "M6"
                        },
                        new
                        {
                            Id = 7,
                            Line = "M7"
                        },
                        new
                        {
                            Id = 8,
                            Line = "M8"
                        },
                        new
                        {
                            Id = 9,
                            Line = "M9"
                        },
                        new
                        {
                            Id = 10,
                            Line = "M10"
                        });
                });

            modelBuilder.Entity("LostAndFoundApp.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KapiID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LostItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineCodeId");

                    b.HasIndex("LostItemId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KapiID = "A1",
                            LineCodeId = 1
                        },
                        new
                        {
                            Id = 2,
                            KapiID = "B2",
                            LineCodeId = 2
                        },
                        new
                        {
                            Id = 3,
                            KapiID = "C3",
                            LineCodeId = 3
                        },
                        new
                        {
                            Id = 4,
                            KapiID = "D4",
                            LineCodeId = 1
                        },
                        new
                        {
                            Id = 5,
                            KapiID = "E5",
                            LineCodeId = 2
                        });
                });

            modelBuilder.Entity("LostAndFoundApp.Models.LostItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoundBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FoundDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LineCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineCodeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("LostItems");
                });

            modelBuilder.Entity("LostAndFoundApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "password1",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 3,
                            Password = "password2",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = 4,
                            Password = "test123",
                            UserName = "test"
                        },
                        new
                        {
                            Id = 5,
                            Password = "demo123",
                            UserName = "demo"
                        });
                });

            modelBuilder.Entity("LostAndFoundApp.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LineCode = "M1",
                            PlateNumber = "34 ABC 123"
                        },
                        new
                        {
                            Id = 2,
                            LineCode = "M2",
                            PlateNumber = "34 DEF 456"
                        },
                        new
                        {
                            Id = 3,
                            LineCode = "M3",
                            PlateNumber = "34 GHI 789"
                        },
                        new
                        {
                            Id = 4,
                            LineCode = "M4",
                            PlateNumber = "34 JKL 012"
                        },
                        new
                        {
                            Id = 5,
                            LineCode = "M5",
                            PlateNumber = "34 MNO 345"
                        },
                        new
                        {
                            Id = 6,
                            LineCode = "M6",
                            PlateNumber = "34 PQR 678"
                        },
                        new
                        {
                            Id = 7,
                            LineCode = "M7",
                            PlateNumber = "34 STU 901"
                        },
                        new
                        {
                            Id = 8,
                            LineCode = "M8",
                            PlateNumber = "34 VWX 234"
                        },
                        new
                        {
                            Id = 9,
                            LineCode = "M9",
                            PlateNumber = "34 YZA 567"
                        },
                        new
                        {
                            Id = 10,
                            LineCode = "M10",
                            PlateNumber = "34 BCD 890"
                        });
                });

            modelBuilder.Entity("LostAndFoundApp.Models.Location", b =>
                {
                    b.HasOne("LostAndFoundApp.Models.LineCode", "LineCode")
                        .WithMany("Locations")
                        .HasForeignKey("LineCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LostAndFoundApp.Models.LostItem", "LostItem")
                        .WithMany("Locations")
                        .HasForeignKey("LostItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LineCode");

                    b.Navigation("LostItem");
                });

            modelBuilder.Entity("LostAndFoundApp.Models.LostItem", b =>
                {
                    b.HasOne("LostAndFoundApp.Models.LineCode", "LineCode")
                        .WithMany("LostItems")
                        .HasForeignKey("LineCodeId");

                    b.HasOne("LostAndFoundApp.Models.Vehicle", null)
                        .WithMany("LostItems")
                        .HasForeignKey("VehicleId");

                    b.Navigation("LineCode");
                });

            modelBuilder.Entity("LostAndFoundApp.Models.LineCode", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("LostItems");
                });

            modelBuilder.Entity("LostAndFoundApp.Models.LostItem", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("LostAndFoundApp.Models.Vehicle", b =>
                {
                    b.Navigation("LostItems");
                });
#pragma warning restore 612, 618
        }
    }
}
